// src/components/AboutUs.jsx
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Brain, Route, HelpCircle, Target, Sparkles } from 'lucide-react';

export default function AboutUs() {
  var navigate = useNavigate();

  return (
    <div className="static-page">
      <div className="static-page-container">
        <button className="static-back-btn" onClick={function () { navigate(-1); }}>
          <ArrowLeft size={18} /> Back
        </button>

        <div className="static-page-header">
          <h1>About LearnPath.ai</h1>
          <p className="static-subtitle">AI-powered learning, personalized for you.</p>
        </div>

        <div className="static-page-content">
          <section className="static-section">
            <div className="static-section-icon">
              <Brain size={24} />
            </div>
            <h2>What is LearnPath.ai?</h2>
            <p>
              LearnPath.ai is an intelligent learning platform that uses artificial intelligence
              to create personalized learning experiences. Whether you want to learn programming,
              science, history, or any other topic — our AI generates structured learning paths
              tailored to your goals and pace.
            </p>
          </section>

          <section className="static-section">
            <div className="static-section-icon">
              <Route size={24} />
            </div>
            <h2>Personalized Learning Paths</h2>
            <p>
              Tell us what you want to learn and how many days you have. Our AI creates a
              complete curriculum with structured lessons, breaking down complex topics into
              digestible, progressive steps. Each path adapts to your chosen timeframe,
              ensuring you learn at a comfortable pace.
            </p>
          </section>

          <section className="static-section">
            <div className="static-section-icon">
              <Sparkles size={24} />
            </div>
            <h2>AI-Generated Lessons</h2>
            <p>
              Every lesson is generated by advanced AI models, providing clear explanations,
              real-world examples, and practical insights. Lessons are created on-demand,
              ensuring fresh and relevant content every time you learn.
            </p>
          </section>

          <section className="static-section">
            <div className="static-section-icon">
              <HelpCircle size={24} />
            </div>
            <h2>Interactive Quizzes</h2>
            <p>
              Test your understanding with AI-generated quizzes placed throughout your learning
              path. Quizzes include multiple-choice questions that assess your comprehension
              and help reinforce key concepts. Get instant feedback and track areas that need
              more review.
            </p>
          </section>

          <section className="static-section">
            <div className="static-section-icon">
              <Target size={24} />
            </div>
            <h2>Track Your Progress</h2>
            <p>
              Stay motivated with XP points, streaks, achievements, and detailed progress
              tracking. See how far you have come, identify areas for improvement, and
              celebrate your learning milestones along the way.
            </p>
          </section>

          <div className="static-footer-note">
            <p>
              Built with ❤️ to make learning accessible, engaging, and effective for everyone.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}